---
- name: Provision EC2 and deploy website
  hosts: aws
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy website files
      copy:
        src: ./site/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0755

    - name: Allow HTTP through UFW
      ufw:
        rule: allow
        name: "Apache Full"
